package com.restaurant.restaurantapp.DTO;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CreateRazorpayOrderResponseDTO {
    private String razorpayOrderId; // The order_id generated by Razorpay
    private String razorpayKeyId;   // Your Razorpay Key ID (to be passed to Razorpay Checkout options)
    private Long amountInPaise;     // Amount in the smallest currency unit (e.g., paise for INR)
    private String currency;        // e.g., "INR"
    // You can add your internal order ID here too if needed for frontend reference
    // private String applicationOrderId;
}